name: Docker image builds (pull requests)

on:
  pull_request:
    branches: ["main"]

env:
  DOCKER_METADATA_SET_OUTPUT_ENV: "true"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - uses: ko-build/setup-ko@v0.8

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/j0lol/anubis

      - name: Build and push
        id: build
        run: |
          go run ./cmd/containerbuild --docker-repo ghcr.io/j0lol/anubis --slog-level debug
        env:
          PULL_REQUEST_ID: ${{ github.event.number }}

      - run: |
          echo "Test this with:"
          echo "docker pull ${{ steps.build.outputs.docker_image }}"
